package com.example.demo.controller;

import com.example.demo.HelloService;
import com.example.demo.model.dto.HelloDto;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import java.util.Collection;

@Validated
@CrossOrigin(origins = "http://localhost:9500")
@RestController
public class HelloController {
	@Autowired
	private HelloService helloService;

	@GetMapping("/hellos")
	public Collection<HelloDto> getHellos() {
		return helloService.getAllHellos();
	}

	@PostMapping("/hellos")
	public void addHello(@RequestBody HelloDto helloDTO) {
		helloService.addHello(helloDTO);
	}

	@DeleteMapping("/hellos/{id}")
	public void deleteHello(@PathVariable String id) {
		helloService.deleteHello(id);
	}

	@PutMapping("/hellos/{id}")
	public void updateHello(@PathVariable String id, @RequestBody HelloDto helloDTO){
		helloService.updateHello(id,helloDTO);
	}

//	MS token manager
	//generar credenciales -> devuelven token
	//pedir token (basado en credenciales)
	//Token tiene duración ms (3600)

	//request token

	//POST {{tokenMgmtUrl}}/token/
	//Headers:
		//env dev, qa, prod [post]
		//key
		//secret asdokjasldkjaslkdjasdoij234

	//Devuelve token JWT {duration: 3600ms, token: "Bearer Jwtlaksjdlkasjdlkjasldkjaslkdjasp234324"}

	//MSAlumnos por cada petición envío token
	//GET url/alumnos
	//HEADER Authorization JWT

	//NamelessEntity
		//String key
		//String secret (autogenerated)
		//String env
		//Token token

	//TokenEntity
		//LocalDateTime time
		//JWT jwt

}
